apiVersion: v2
name: fluxer-helm
description: Helm chart for Fluxer (fluxerapp/fluxer)
version: 0.3.0
appVersion: "2026.820"
home: https://github.com/antoniolago/fluxer-helm
sources:
  - https://github.com/antoniolago/fluxer-helm
keywords:
  - fluxer
  - chat
  - messaging
  - voip
  - self-hosted
type: application
maintainers:
  - name: Antônio Lago
