{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluxer.secretName" . }}
  namespace: {{ include "fluxer.namespace" . }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.secretData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
